Add zenodo metadata file
soft-matter/trackpy pull request #661
Opened 2021-04-13 18:52 UTC by caspervdw

This file should be picked up by Zenodo to automatically set the creators and license fields. I had to manually set them for the last release (and I got an internal server error from Zenodo while doing it - will see if I can fix that).

I think it is justified to add @rbnvrw to the list of authors as he did a major contribution in #527.

2021-04-14 00:57 UTC, nkeim requested changes
Thanks! 👍 for adding Ruben.

2021-04-14 00:57 UTC, nkeim commented on .zenodo.json
> +            "affiliation": "California Polytechnic State University",
Since only one affiliation is allowed, please change to `"Pennsylvania State University"`.

2021-04-16 06:00 UTC, rbnvrw approved these changes
Great, thank you @caspervdw !
And congratulations all on the new release :+1:

2021-04-16 11:16 UTC, caspervdw commented on .zenodo.json
> +            "affiliation": "California Polytechnic State University",
```suggestion
            "affiliation": "Pennsylvania State University", 
```

2021-04-16 11:16 UTC, merged